### PR TITLE
[T] (quests) Sanguine Sting

### PR DESCRIPTION
**Pull request by Ricky-fight**
Co-authored-by: VictorXie <sipengxie@buaa.edu.cn>
Co-authored-by: lee <527132183@qq.com>
Co-authored-by: 吞个米诺陶 <1709969037@qq.com>
Co-authored-by: 小兔崽子 <1964245709@qq.com>
Co-authored-by: 努力 <nuli_dingpeng@163.com>
Co-authored-by: LANLAN <a1012881806@gmail.com>
Co-authored-by: 青丘雨 <1040214676@qq.com>
Co-authored-by: 氵夕言汐 <z13409823660@126.com>

### CODE REVIEW

**Comment by Ricky-fight** [comment]
TODO：
- [ ] 补协作邮箱

**Comment by nai200** [comment]
吞个米诺陶 1709969037@qq.com
小兔崽子 1964245709@qq.com

**Comment by nai200** [comment]
Co-authored-by: 小兔崽子 <1964245709@qq.com>
Co-authored-by: 淡蓝の恋 <1291252824qq@gmail.com>

**Comment by nai200** [comment]
Co-authored-by: 吞个米诺陶 <1709969037@qq.com>
Co-authored-by: 小兔崽子 <1964245709@qq.com>

**Pull request merged**
